SALES_QUERY = "SALES_QUERY_PLACEHOLDER"
PRODUCTS_QUERY = "PRODUCTS_QUERY_PLACEHOLDER"
STOCK_QUERY = "STOCK_QUERY_PLACEHOLDER"
PURCHASES_QUERY = "PURCHASES_QUERY_PLACEHOLDER"

DATASET_QUERIES = {
    "sales": SALES_QUERY,
    "products": PRODUCTS_QUERY,
    "stock": STOCK_QUERY,
    "purchases": PURCHASES_QUERY,
}
